name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore BlubbiChanged --nologo 
    - name: Build
      run: dotnet build BlubbiChanged --nologo --no-restore -c Release
    - name: Test
      run: dotnet test BlubbiChanged --nologo --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish BlubbiChanged/BlubbiChanged/BlubbiChanged.csproj --nologo --no-build -c Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4  
      with: 
        path: BlubbiChanged/BlubbiChanged/bin/Release/netstandard2.0/publish/*.*
    - name: dotnet pack
      run: dotnet pack BlubbiChanged/BlubbiChanged/BlubbiChanged.csproj --nologo --no-build -c Release
    - name: nuget push
      run: dotnet nuget push BlubbiChanged/BlubbiChanged/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
